tasks/urls.py
# tasks.ulrs.py
from django.urls import path
from . import views

urlpatterns = [
    path('helloWorld/', views.helloWorld),
    path('', views.taskList, name='task-list'),
    path('newtask/', views.newTask, name='new-task'),
    path('edittask/<int:id>', views.editTask, name='edit-task'),
    path('task/<int:id>', views.taskView, name="task-view"),
    path('delete/<int:id>', views.deleteTask, name="delete-task"),
    path('yourname/<str:name>', views.yourName, name='your-name'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('', include('clients.urls')),
    path('', include('servers.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Task(models.Model):
    
    STATUS = (
        ('Fazendo', 'Fazendo'),
        ('Feito', 'Feito'),
    )

    title = models.CharField(max_length=255)
    descripition = models.TextField()
    done = models.CharField(
        max_length=15, 
        choices=STATUS,
        )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'descripition')
        

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import TaskForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import Task

#list all tasks
@login_required
def taskList(request):

    #busca
    search = request.GET.get('search')
    if search:
        tasks = Task.objects.filter(title__icontains=search, user=request.user)

    else:   

        #find elements all for paginator
        tasks_list = Task.objects.all().order_by('-create_at').filter(user=request.user)
        paginator = Paginator(tasks_list, 3)

        page = request.GET.get('page')
        tasks = paginator.get_page(page)

    return render(request, 'tasks/list.html', {'tasks':tasks})

#view task isolate
@login_required
def taskView(request, id):
    task = get_object_or_404(Task, pk=id)
    return render(request, 'tasks/task.html', {'task': task})

# create task
@login_required
def newTask(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            task = form.save(commit=False)
            task.done = 'Fazendo'
            task.user = request.user
            task.save()
            return redirect('/')

    else:
        form = TaskForm()
        return render(request, 'tasks/addtask.html', {'form': form})

#edit task
@login_required
def editTask(request, id):
    task = get_object_or_404(Task, pk=id)
    form = TaskForm(instance=task)

    if (request.method == 'POST'):
        form = TaskForm(request.POST, instance=task)
        
        if (form.is_valid()):
            task.save()
            return redirect('/')
        else:
            return render(request, 'tasks/edittask.html', {'form': form, 'task': task})
    else:
        return render(request, 'tasks/edittask.html', {'form': form, 'task': task}) 

# delete task
@login_required
def deleteTask(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    messages.info(request, 'Tarefa deletada com sucesso.')
    return redirect('/')

def helloWorld(request):
    return HttpResponse('Hello World!')

def yourName(request, name):
    return render(request, 'tasks/yourname.html', {'name':name})

tasks/templates/tasks/addtask.html
{% extends 'base.html' %}
{% block title %} Nova Tarefa{% endblock %}
{% block content %}

<div class="row">
 

        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1">Titulo</label>
                <input class="form-control" type="text" name="title" maxlength="255" required="" id="id_title">
            </div>
            <br>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Descriçao</label>
                <textarea class="form-control" rows="3" name="descripition" id="id_descripition"></textarea>
            </div>
            <br>

            <button class="btn btn-primary" type="submit">Nova Tarefa</button>
        </form>
   

</div>

{% endblock %}

tasks/templates/tasks/edittask.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %}{{task.title}}{% endblock %}

{% block content %}
<div class="row">
    <h1>Editando '{{task.title}}'</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Editar Tarefa">
    </form>
</div>
{% endblock %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block title %} Lista de Tarefas {% endblock %}

{% block content %}
{% load humanize %}
<div class="row">

    <div class="col col-sm-9">
        <!-- <form method="GET" id="search-form">
                    <input class="form-control" type="text" id="search" name="search" placeholder="Digite o nome da tarefa para buscar..." value="{{ request.GET.search }}">
                    <i class="fas fa-search" id="search-btn"></i>
                </form> -->
        <form method="GET" id="search-form">
            <!-- <label for="exampleDataList" class="form-label">Datalist example</label> -->
            <input class="form-control" list="datalistOptions" placeholder="Digita aqui pra pesquisar..." type="text"
                id="search" value="{{ request.GET.search }}" name="search">
            <datalist id="datalistOptions">
                <option value="San Francisco">
                <option value="New York">
                <option value="Seattle">
                <option value="Los Angeles">
                <option value="Chicago">
            </datalist>
        </form>
        <!-- <div class="form-group has-search">
                    <span class="fa fa-search form-control-feedback"></span>
                    <input type="text" class="form-control" placeholder="Pesquisar">
                  </div> -->
        <!-- <div class="input-group flex-nowrap">
                    <span class="input-group-text" id="addon-wrapping">PESQUISAR</span>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
                  </div> -->
    </div>

    <div class="col col-sm text-end">
        <a class="btn btn-primary" href="newtask/" role="button">Nova Tarefa</a>
    </div>

</div>

<br>

<div class="list-group">
    {% for task in tasks %}
    <a href="task/{{ task.id }}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
            <h4 class="mb-1">{{ task.title }} </h4>
            <small class="text-muted">{{ task.update_at|naturaltime }}</small>
        </div>
        <p class="mb-1 limit" id="mydiv">{{ task.descripition }}</p>
        <small class="text-muted">{{ task.done }}</small>
    </a>
    {% endfor %}
    <a href="#" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">List group item heading</h5>
            <small class="text-muted">3 days ago</small>
        </div>
        <p class="mb-1">Some placeholder content in a paragraph.</p>
        <small class="text-muted">And some muted small print.</small>
    </a>
    <a href="#" class="list-group-item list-group-item-action active">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">List group item heading</h5>
            <small class="text-muted">3 days ago</small>
        </div>
        <p class="mb-1">Some placeholder content in a paragraph.</p>
        <small class="text-muted">And some muted small print.</small>
    </a>
</div>
<br>



<nav aria-label="Page navigation example">
    <ul class="pagination  justify-content-center">
        {% if tasks.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ tasks.previous_page_number }}">Anterior</a>
        </li>
        {% endif %}

        {% if tasks.paginator.num_pages%}
        <li class="page-item"><a class="page-link" href="#">{{ tasks.number }} de {{ tasks.paginator.num_pages}}</a>
        </li>
        {% endif %}

        {% if tasks.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ tasks.next_page_number }}">Próximo</a></li>
        {% endif %}
    </ul>
</nav>


{% endblock %}

tasks/templates/tasks/task.html
{% extends 'base.html' %}
{% block title %} Tarefa: {% endblock %}

{% block content %}
{% load humanize %}
<div class="p-5 mb-2 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">{{ task.title }}</h1>
    <p class="col-md-9 fs-4">{{ task.descripition }}</p>
    <!-- <button class="btn btn-primary btn-lg" type="button">Example button</button> -->
    <small>{{ task.update_at|naturaltime }}</small>

    <br>
    <a class="text-decoration-none" href="/edittask/{{ task.id }}">Editar Tarefa </a>
    <a class="text-decoration-none" href="/delete/{{ task.id }}">| Deletar Tarefa</a>

  </div>
</div>
{% endblock %}

tasks/templates/tasks/yourname.html
{% extends 'base.html' %}
{% block title %} Qual seu nome:{% endblock %}



{% block content %}
the name is {{ name }}
{% endblock %}